### PR TITLE
Avoid motor block with safe compliance at startup

### PR DESCRIPTION
**Pull request by show0k**

### CODE REVIEW

**Comment by jjehl** [comment]
If I understand your changes, when the robot is in a strange position (I mean out of angles limit), the motors block ?

**Comment by show0k** [comment]
Exactly. The "safe" compliance is blocking motors if they go out of range. But if the motor start out of range, it will sometimes be blocked and cannot return on the range. 
This is more a hack than a fix, it just reduces the occurrence of this issue. We should investigate more and change the safe compliance code.

**Comment by jjehl** [comment]
Maybe you can merge your request and after we'll merge the branch dev because the update I made about  V-REP scene in dev branche is a big change we have to put on master (essential to use V-REP)

**Comment by jjehl** [comment]
Safe compliance was desactivate in an other commit, so I think we have no more needs to merge this request.

**Pull request closed without merging**
