### PR TITLE
Optimized V-REP model

### PR DESCRIPTION
**Pull request by matthieu-lapeyre**
To discuss before merge on master:

@sebastien-forestier, @pierre-rouanet, @show0k 
Do we use the same zero position on the Humanoid and Torso for the elbow joint ?

pro: code is cross-compatible between creature
bad: the zero position is not possible because it leads to contact with the table

### CODE REVIEW

**Comment by show0k** [comment]
I already change the zero position on the configuration file in #4 (see 5f14d2e251f2abc8178931a3d73e7b8c20a89738) to avoid contact with table.

**Comment by matthieu-lapeyre** [comment]
@jjehl prefers to keep the compatibility with the Humanoid so the same code work for both. It is a point.

In this merge, the v-rep model use the same convention as the Humanoid. Before merging this PR on master, I would like to have all opinions to decide if we modify it or not.

**Comment by pierre-rouanet** [comment]
I don't have a strong opinion on this. Both ways have pros and cons. 

We should especially see with @sebastien-forestier and @Tibo42, they already start working with the Torso and V-REP they may have the strongest opinion on the matter (and maybe they don't wan't to change their code).

**Comment by oudeyer** [comment]
My intuition is that a zero position that does not collide with the table is better

**Comment by sebastien-forestier** [comment]
So far in my code I used a 'rest position' different from the 'zero position', for the elbow joints but also for other joints I wanted to rest elsewhere, for instance l_arm_z and r_arm_z.
I think it is clearer to have a 'rest position' than a 'zero position', and furthermore that can be tuned.
Then, this rest position doesn't need to be zero, and for compatibility with Humanoid, I would say it would be better to keep the same zero values.

**Comment by jjehl** [comment]
Agree with the rest-position different from the zero position. We also have to be careful with snap example I just read yesterday with  blocks "all motors goto position 0"

**Comment by show0k** [comment]
@jjehl That exactly why I changed the zero position in the conf file. It's exhausting for newbies to make all motors minus two goto zero position. The rest position is interesting but it add a new "concept".
Another solution, suggested by @matthieu-lapeyre is to add a forward kinematics model to avoid contacts with table.

**Comment by jjehl** [comment]
So, let's go with a zero position without contact with table. Just tested five minutes ago and it's works, @matthieu-lapeyre can you merge in master.

**Pull request merged**
